-- ============================================================
-- 001 — SAD_ISSUES: one row per issue
--
-- SAD_ISSUES was keyed on (ISSUE_KEY, SPRINT_NAME), so a ticket that moved sprint got
-- a new row and the old one stayed, frozen at its old status. Loading from the
-- database then counted moved tickets once per sprint they had been in.
--
-- ORDER MATTERS: restart the backend on the new code (npm run restart:pm2) BEFORE
-- running this. The old code inserts a new row when a ticket changes sprint, which
-- would violate UQ_ISSUE_KEY and fail every save.
--
-- Run in SQL Developer connected as SprintAnalyticsDashboard. Steps 1–2 are safe to
-- re-run; check the counts after step 1 before going on.
-- ============================================================

-- ── 1. Back up the rows that will be removed ─────────────────
-- Everything except the newest row per issue (latest FETCHED_AT, then highest ID),
-- the same row the backend now reads and keeps.
CREATE TABLE SAD_ISSUES_DUP_BACKUP AS
  SELECT * FROM SAD_ISSUES
  WHERE ID NOT IN (
    SELECT MAX(ID) KEEP (DENSE_RANK LAST ORDER BY FETCHED_AT)
    FROM SAD_ISSUES GROUP BY ISSUE_KEY
  );

-- Expect: backup rows = total rows - distinct issues.
SELECT (SELECT COUNT(*) FROM SAD_ISSUES_DUP_BACKUP)       AS BACKED_UP,
       (SELECT COUNT(*) FROM SAD_ISSUES)                  AS TOTAL_ROWS,
       (SELECT COUNT(DISTINCT ISSUE_KEY) FROM SAD_ISSUES) AS ISSUES
FROM DUAL;

-- ── 2. Remove them ───────────────────────────────────────────
DELETE FROM SAD_ISSUES WHERE ID IN (SELECT ID FROM SAD_ISSUES_DUP_BACKUP);
COMMIT;

-- ── 3. One row per issue from now on ─────────────────────────
ALTER TABLE SAD_ISSUES DROP CONSTRAINT UQ_ISSUE_KEY_SPRINT DROP INDEX;
ALTER TABLE SAD_ISSUES ADD CONSTRAINT UQ_ISSUE_KEY UNIQUE (ISSUE_KEY);

-- ── Undo (only if needed) ────────────────────────────────────
-- ALTER TABLE SAD_ISSUES DROP CONSTRAINT UQ_ISSUE_KEY DROP INDEX;
-- ALTER TABLE SAD_ISSUES ADD CONSTRAINT UQ_ISSUE_KEY_SPRINT UNIQUE (ISSUE_KEY, SPRINT_NAME);
-- INSERT INTO SAD_ISSUES SELECT * FROM SAD_ISSUES_DUP_BACKUP;   -- ID is GENERATED ALWAYS:
--   use INSERT ... (cols) SELECT cols, or ALTER the column to GENERATED BY DEFAULT first.
-- COMMIT;
--
-- Once happy, the backup can go:  DROP TABLE SAD_ISSUES_DUP_BACKUP PURGE;
