-- ============================================================
-- Sprint Analytics Dashboard - Oracle DDL
-- Schema: SprintAnalyticsDashboard
-- Run this in SQL Developer connected as SprintAnalyticsDashboard
-- ============================================================

-- ── 1. JIRA ISSUES (raw ticket data) ─────────────────────────
CREATE TABLE SAD_ISSUES (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ISSUE_KEY       VARCHAR2(50)   NOT NULL,
  SUMMARY         VARCHAR2(1000),
  ISSUE_TYPE      VARCHAR2(100),
  STATUS          VARCHAR2(100),
  ASSIGNEE        VARCHAR2(255),
  PROJECT_KEY     VARCHAR2(50),
  PROJECT_NAME    VARCHAR2(255),
  SPRINT_NAME     VARCHAR2(500),
  STORY_POINTS    NUMBER(10,2),
  ORIGINAL_EST    NUMBER,
  PRIORITY        VARCHAR2(50),
  LABELS          VARCHAR2(1000),
  COMPONENTS      VARCHAR2(1000),
  CREATED_DATE    DATE,
  UPDATED_DATE    DATE,
  FETCHED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_ISSUE_KEY_SPRINT UNIQUE (ISSUE_KEY, SPRINT_NAME)
);

-- ── 2. SPRINTS ────────────────────────────────────────────────
CREATE TABLE SAD_SPRINTS (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SPRINT_NAME     VARCHAR2(500)  NOT NULL UNIQUE,
  START_DATE      DATE,
  END_DATE        DATE,
  STATE           VARCHAR2(50),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ── 3. ASSIGNEE CAPACITY CONFIG ───────────────────────────────
CREATE TABLE SAD_ASSIGNEE_CAPACITY (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ASSIGNEE        VARCHAR2(255)  NOT NULL UNIQUE,
  SPRINT_CAPACITY NUMBER(10,2)   DEFAULT 16 NOT NULL,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ── 4. ASSIGNEE ELIGIBILITY (project access per person) ───────
CREATE TABLE SAD_ELIGIBILITY (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ASSIGNEE        VARCHAR2(255)  NOT NULL,
  PROJECT_KEY     VARCHAR2(50)   NOT NULL,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_ELIGIBILITY UNIQUE (ASSIGNEE, PROJECT_KEY)
);

-- ── 5. ROLES & RESPONSIBILITIES ───────────────────────────────
CREATE TABLE SAD_ROLES (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROLE_ID         VARCHAR2(50)   NOT NULL UNIQUE,
  TITLE           VARCHAR2(255)  NOT NULL,
  BULLETS         CLOB,
  RESPONSIBLE     VARCHAR2(500),
  SORT_ORDER      NUMBER DEFAULT 0,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ── 6. ALLOCATION CHANGES (board drag-drop saves) ─────────────
CREATE TABLE SAD_ALLOCATIONS (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SPRINT_NAME     VARCHAR2(500),
  ISSUE_KEY       VARCHAR2(50)   NOT NULL,
  FROM_ASSIGNEE   VARCHAR2(255),
  TO_ASSIGNEE     VARCHAR2(255),
  STORY_POINTS    NUMBER(10,2),
  ALLOCATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ── 7. DASHBOARD SETTINGS (misc key/value store) ──────────────
CREATE TABLE SAD_SETTINGS (
  SETTING_KEY     VARCHAR2(100)  NOT NULL PRIMARY KEY,
  SETTING_VALUE   CLOB,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ── Indexes ───────────────────────────────────────────────────
CREATE INDEX IDX_ISSUES_ASSIGNEE  ON SAD_ISSUES(ASSIGNEE);
CREATE INDEX IDX_ISSUES_SPRINT    ON SAD_ISSUES(SPRINT_NAME);
CREATE INDEX IDX_ISSUES_PROJECT   ON SAD_ISSUES(PROJECT_KEY);
CREATE INDEX IDX_ISSUES_STATUS    ON SAD_ISSUES(STATUS);
CREATE INDEX IDX_ALLOC_SPRINT     ON SAD_ALLOCATIONS(SPRINT_NAME);

COMMIT;
